2018-04-20 15:07:15,083 ERROR: Exception on /uploader [POST] [in /home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mark/PythonFlaskVertica/app/routes.py", line 723, in upload_file
    line = Project(line)
TypeError: __init__() takes 1 positional argument but 2 were given
2018-04-20 15:07:46,407 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:49]
2018-04-20 15:07:46,408 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-20 15:07:46,408 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-20 17:02:57,401 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:49]
2018-04-20 17:02:57,401 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-20 17:02:57,401 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-20 17:03:54,945 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:49]
2018-04-20 17:03:54,946 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-20 17:03:54,946 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-20 17:09:03,301 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:49]
2018-04-20 17:09:03,302 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-20 17:09:03,302 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-20 17:34:09,085 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:49]
2018-04-20 17:34:09,086 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-20 17:34:09,086 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 13:42:36,163 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:49]
2018-04-22 13:42:36,163 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 13:42:36,163 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 13:44:43,225 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:49]
2018-04-22 13:44:43,225 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 13:44:43,225 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 13:45:42,390 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:49]
2018-04-22 13:45:42,390 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 13:45:42,390 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 13:55:21,407 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:49]
2018-04-22 13:55:21,408 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 13:55:21,408 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 14:07:53,138 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:49]
2018-04-22 14:07:53,139 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 14:07:53,139 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 14:24:29,054 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:49]
2018-04-22 14:24:29,055 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 14:24:29,055 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 14:31:40,998 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:49]
2018-04-22 14:31:40,999 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 14:31:40,999 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 14:31:50,258 ERROR: Exception on /view_projects [GET] [in /home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mark/PythonFlaskVertica/app/routes.py", line 145, in view_projects
    all_proj = db.session.query(Project).outerjoin(DbObject, Project.pid == DbObject.project_id).all().order_by(Project.pid)
AttributeError: 'list' object has no attribute 'order_by'
2018-04-22 14:31:50,258 ERROR: Exception on /view_projects [GET] [in /home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mark/PythonFlaskVertica/app/routes.py", line 145, in view_projects
    all_proj = db.session.query(Project).outerjoin(DbObject, Project.pid == DbObject.project_id).all().order_by(Project.pid)
AttributeError: 'list' object has no attribute 'order_by'
2018-04-22 14:40:54,138 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:49]
2018-04-22 14:40:54,139 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 14:40:54,139 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 14:41:55,289 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:49]
2018-04-22 14:41:55,290 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 14:41:55,290 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 14:44:40,971 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:49]
2018-04-22 14:44:40,972 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 14:44:40,972 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 15:02:03,320 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:49]
2018-04-22 15:02:03,327 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 15:02:03,327 INFO: Pride2 startup [in /home/mark/PythonFlaskVertica/app/__init__.py:67]
2018-04-22 15:02:08,683 ERROR: Exception on /view_projects [GET] [in /home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mark/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mark/PythonFlaskVertica/app/routes.py", line 144, in view_projects
    all_proj = db.session.query(Project).outerjoin(DbObject, Project.pid == DbObject.project_id).all().order_by(Project.pid)
AttributeError: 'list' object has no attribute 'order_by'
